name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://clustertest-http-vault-4bc39b71.j.cloud.hashicorp.com
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t vault-action-exampleapp

