name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vault
        run: |
          # Download and install Vault
          curl -LO https://releases.hashicorp.com/vault/<vault-version>/vault_<vault-version>_linux_amd64.zip
          unzip vault_<vault-version>_linux_amd64.zip
          sudo mv vault /usr/local/bin/
        env:
          vault-version: 1.8.0 # Use the specific version of Vault you need


      - name: Set up Vault Secrets
        env:
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          echo "VAULT_ROLE_ID=$VAULT_ROLE_ID" >> $GITHUB_ENV
          echo "VAULT_SECRET_ID=$VAULT_SECRET_ID" >> $GITHUB_ENV

      # Now you can use the Vault secrets in your subsequent steps.


      - name: Retrieve Secret from Vault
        run: |
          VAULT_TOKEN=$(vault write auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)
          MY_SECRET=$(kv-get -field=my-token kv/test/webapp)
          echo "My secret is: $MY_SECRET"



